### ISSUE TITLE
In app file selection not working

### ISSUE THREAD

**Issue by itsUrcute** [adrifcastr/ImageLink#10]
Selecting a file for upload using the `select file` button on the main screen doesn't seem to work properly.
The file appears on the screen for a split second but is then gone, rendering it impossible to select and upload files in app.
Tested with multiple file types but none work.
**note:** *upload works fine with sharing into the app*

App version: 0.4.0
OS version: Android 10
Phone: Vivo y50

you can see the issue recorded [here](https://au.adnauseam.xyz/55kvc96marf4.mp4).

**Comment by castdrian** [comment]
It's not actually a crash, it's reloading the navbar instance, because it's returning from the background process, need to not do that when selecting a file
